# -*- coding: utf-8 -*-
"""Checkpoint1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yj5sPHAu0598KPwaYdIOg_cP-pggVJ1g

# News Article Categorizer — Checkpoint 1

GROUP MEMBERS NAME

JAGADESH (A24AI0035)

MUHAMMAD SAFRUL ROSLI (A24AI0064)

CHENG  HAO WEN (A24AI0022)

# Import Required Libraries
"""

import os
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

"""# Dataset Download and Loading (20 Newsgroups)"""

import kagglehub

path = kagglehub.dataset_download("crawford/20-newsgroups")
print(path)

"""# Data Preprocessing and DataFrame Construction"""

data = []

for file in os.listdir(path):
    if not file.endswith(".txt"):
        continue

    label = file.replace(".txt", "")
    file_path = os.path.join(path, file)

    with open(file_path, encoding="latin1") as f:
        content = f.read()

    articles = content.split("From:")

    for article in articles:
        article = article.strip()

        if len(article.split()) < 20:
            continue

        data.append([article, label])

df = pd.DataFrame(data, columns=["text", "label"])

print(df.shape)
df.head()

df["label"].value_counts().plot(kind="bar", figsize=(12,5))
plt.title("Category Distribution")
plt.xticks(rotation=90)
plt.show()

"""# Text Cleaning and NLP Preprocessing"""

nltk.download("stopwords")
nltk.download("wordnet")

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [lemmatizer.lemmatize(w) for w in words]

    return " ".join(words)

df["clean_text"] = df["text"].apply(clean_text)

print("Preprocessing done")

"""# Train-Test Split"""

X = df["clean_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

"""# Feature Extraction Using TF-IDF Vectorization"""

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF:", X_train_tfidf.shape)

"""# Feature Extraction Using Bag of Words (BoW)"""

bow = CountVectorizer(max_features=5000)

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

print("BoW:", X_train_bow.shape)

"""# Model Training (Naive Bayes & Logistic Regression - TF-IDF)"""

nb_tfidf = MultinomialNB()
nb_tfidf.fit(X_train_tfidf, y_train)
pred_nb_tfidf = nb_tfidf.predict(X_test_tfidf)

lr_tfidf = LogisticRegression(max_iter=1000)
lr_tfidf.fit(X_train_tfidf, y_train)
pred_lr_tfidf = lr_tfidf.predict(X_test_tfidf)

"""# Model Training (Naive Bayes & Logistic Regression - BoW)"""

nb_bow = MultinomialNB()
nb_bow.fit(X_train_bow, y_train)
pred_nb_bow = nb_bow.predict(X_test_bow)

lr_bow = LogisticRegression(max_iter=1000)
lr_bow.fit(X_train_bow, y_train)
pred_lr_bow = lr_bow.predict(X_test_bow)

"""# Model Evaluation Results"""

def evaluate(name, y_true, y_pred):
    print("\n", name)
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print(classification_report(y_true, y_pred))

evaluate("TF-IDF + NB", y_test, pred_nb_tfidf)
evaluate("TF-IDF + LR", y_test, pred_lr_tfidf)
evaluate("BoW + NB", y_test, pred_nb_bow)
evaluate("BoW + LR", y_test, pred_lr_bow)

"""# Performance Comparison Table"""

results = pd.DataFrame({
    "Model": ["TF-IDF + NB", "TF-IDF + LR", "BoW + NB", "BoW + LR"],

    "Accuracy": [
        accuracy_score(y_test, pred_nb_tfidf),
        accuracy_score(y_test, pred_lr_tfidf),
        accuracy_score(y_test, pred_nb_bow),
        accuracy_score(y_test, pred_lr_bow)
    ],

    "Precision": [
        precision_score(y_test, pred_nb_tfidf, average="weighted"),
        precision_score(y_test, pred_lr_tfidf, average="weighted"),
        precision_score(y_test, pred_nb_bow, average="weighted"),
        precision_score(y_test, pred_lr_bow, average="weighted")
    ],

    "Recall": [
        recall_score(y_test, pred_nb_tfidf, average="weighted"),
        recall_score(y_test, pred_lr_tfidf, average="weighted"),
        recall_score(y_test, pred_nb_bow, average="weighted"),
        recall_score(y_test, pred_lr_bow, average="weighted")
    ],

    "F1-Score": [
        f1_score(y_test, pred_nb_tfidf, average="weighted"),
        f1_score(y_test, pred_lr_tfidf, average="weighted"),
        f1_score(y_test, pred_nb_bow, average="weighted"),
        f1_score(y_test, pred_lr_bow, average="weighted")
    ]
})

from IPython.display import display
display(results.round(4))

"""# Confusion Matrix"""

labels = sorted(y.unique())

cm = confusion_matrix(y_test, pred_lr_tfidf, labels=labels)

plt.figure(figsize=(14,10))
sns.heatmap(cm, cmap="Blues", xticklabels=labels, yticklabels=labels, annot=False)

plt.title("Confusion Matrix (TF-IDF + Logistic Regression)")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks(rotation=90)
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

"""# Save Trained Model for Deployment"""

import joblib

joblib.dump(lr_tfidf, "best_model.pkl")
joblib.dump(tfidf, "vectorizer.pkl")

print("Model saved")